### ISSUE TITLE
hashing hashes field instead of value

### ISSUE THREAD

**Issue by Requiae** [alexlancer/Auto-CRUD-Generator-CodeIgniter-4-#1]
In Crud_core.php, if field needs to be hashed the field name is hashed instead of the field value. Can be fixed by replacing 
`$post[$hashIt] = password_hash($hashIt, PASSWORD_DEFAULT);`
with
`$post[$hashIt] = password_hash($post[$hashIt], PASSWORD_DEFAULT);`
on line 288

**Comment by hansratzinger** [comment]
Thanks Scott! Please close this issue!
You can clone from my fork all known fixed issuses:
https://github.com/hansratzinger/Auto-CRUD-Generator-CodeIgniter-4-.git
